### PR TITLE
Added Add-Edit-Archive-Unarchive-Team_Members Tests file

### PR DESCRIPTION
**Pull request by KaranTikellu7**
Test file added for adding,archiving and unarchiving team member.

### CODE REVIEW

**Comment by prabhakarbattula** [comment]
@KaranTikellu7 

Update your PR as per feedback.
https://www.useloom.com/share/ed420f488a70404791925da622d81332

**Comment by prabhakarbattula** [comment]
@KaranTikellu7 

Please update PR as per feedback.
https://www.useloom.com/share/f328067cec5243ec9cf998a686b0c6fb

**Comment by prabhakarbattula** [comment]
@KaranTikellu7 

Please extract random, same as you did for login, to common file.

**Comment by KaranTikellu7** [comment]
Unable to replace the expression with variable in xpath as it disturb the xpath because having arithmetic operator at beginning and at end.

**Comment by prabhakarbattula** [comment]
@KaranTikellu7 

Not understanding this https://github.com/prabhakarbattula/aceinvoice-selenium-karan/pull/5#issuecomment-441551053.  Can you post a video explaining it.

**Comment by KaranTikellu7** [comment]
@prabhakarbattula No I solved that problem and I updated the file.

**Pull request merged**
